"""Regenerates src/ui_glyphs.inc: every non-ASCII character that appears in src/*.cpp and src/*.h, so that the font atlas contains the glyphs the UI
text uses even where they fall outside ImGui's "common Chinese" range (for example the characters for "engine" and "button"). The atlas is built once
when the engine's ImGui starts and cannot take glyphs later. Run after changing UI strings:

    python tools/gen_ui_glyphs.py
"""
import glob
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
chars = set()
for path in glob.glob(os.path.join(ROOT, "src", "*.cpp")) + glob.glob(os.path.join(ROOT, "src", "*.h")):
    with open(path, encoding="utf-8") as f:
        chars |= {c for c in f.read() if ord(c) >= 0x80}
text = "".join(sorted(chars))
with open(os.path.join(ROOT, "src", "ui_glyphs.inc"), "w", encoding="utf-8", newline="\n") as f:
    f.write("// GENERATED by tools/gen_ui_glyphs.py from the strings in src/. Do not edit.\n")
    f.write('static const char kUiText[] = "%s";\n' % text)
print(len(chars), "distinct characters")
